CREATE TABLE region (id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(100) NOT NULL, PRIMARY KEY(id));


CREATE TABLE population(id INTEGER GENERATED BY DEFAULT AS IDENTITY, pop INT NOT NULL, PRIMARY KEY(id));


CREATE TABLE country(id INTEGER GENERATED BY DEFAULT AS IDENTITY, country VARCHAR(50) NOT NULL, country_code VARCHAR(30), region_id INTEGER, population_id INTEGER, PRIMARY KEY(id), CONSTRAINT country_region_fk FOREIGN KEY(region_id) REFERENCES region(id), CONSTRAINT coutry_population_fk FOREIGN KEY(population_id) REFERENCES population(id));


CREATE TABLE day(id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(20) NOT NULL, PRIMARY KEY(id));


CREATE TABLE month(id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(20) NOT NULL, PRIMARY KEY(id));


CREATE TABLE year(id INTEGER GENERATED BY DEFAULT AS IDENTITY, name DATE, PRIMARY KEY(id));


CREATE TABLE dates(id INTEGER GENERATED BY DEFAULT AS IDENTITY, start_dt DATE, year_id INT, month_id INT, day_id INT, PRIMARY KEY(id), CONSTRAINT dates_year_fk FOREIGN KEY(year_id) REFERENCES year(id), CONSTRAINT dates_month_fk FOREIGN KEY(month_id) REFERENCES month(id), CONSTRAINT dates_day_fk FOREIGN KEY(day_id) REFERENCES day(id));


CREATE TABLE virus_family(id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(60) NOT NULL,  PRIMARY KEY(id));


CREATE TABLE transmission(id INTEGER GENERATED BY DEFAULT AS IDENTITY, type VARCHAR(60), PRIMARY KEY(id));


CREATE TABLE virus(id INTEGER GENERATED BY DEFAULT AS IDENTITY, name VARCHAR(50) NOT NULL, virus_fam_id INT, tr_id INT, PRIMARY KEY(id), CONSTRAINT virus_virus_family_fk FOREIGN KEY(virus_fam_id) REFERENCES virus_family(id), CONSTRAINT virus_transmission_fk FOREIGN KEY(tr_id) REFERENCES transmission(id));


CREATE TABLE fact_pandemic(dates_id INT, virus_id INT, country_id INT, cases_count INT CHECK (cases_count >= 0), new_cases INT CHECK (new_cases >= 0), recovered_count INT CHECK (recovered_count >= 0), death_count INT CHECK (death_count >= 0), CONSTRAINT fact_pandemic_dates_fk FOREIGN KEY(dates_id) REFERENCES dates(id), CONSTRAINT fact_pandemic_virus_fk FOREIGN KEY(virus_id) REFERENCES virus(id), CONSTRAINT fact_pandemic_country_fk FOREIGN KEY(country_id) REFERENCES country(id));


COMMIT;